export default {
  products: [
    {
      _id: '1',
      name: 'Kagura Tanjiro',
      category: 'COSPLAY',
      image: './images/product-5.jpg',
      price: 100,
      brand: 'DEMON SLAYER',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '1',
      name: 'Kochou Shinobu',
      category: 'COSPLAY',
      image: './images/product-2.jpg',
      price: 100,
      brand: 'DEMON SLAYER',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '1',
      name: 'Rengoku Kyoujurou',
      category: 'COSPLAY',
      image: './images/product-3.jpg',
      price: 100,
      brand: 'DEMON SLAYER',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '1',
      name: 'Enma',
      category: 'COSPLAY',
      image: './images/product-4.jpg',
      price: 100,
      brand: 'ONE PIECE',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '1',
      name: 'Shusui',
      category: 'COSPLAY',
      image: './images/product-1.jpg',
      price: 100,
      brand: 'ONE PIECE',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '1',
      name: 'Wado Ichimoji',
      category: 'COSPLAY',
      image: './images/product-6.jpg',
      price: 100,
      brand: 'ONE PIECEs',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '1',
      name: 'KATANA',
      category: 'COSPLAY',
      image: './images/product-6.jpg',
      price: 100,
      brand: 'DEMON SLAYER',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '1',
      name: 'KATANA',
      category: 'COSPLAY',
      image: './images/product-6.jpg',
      price: 100,
      brand: 'DEMON SLAYER',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '1',
      name: 'KATANA',
      category: 'COSPLAY',
      image: './images/product-2.jpg',
      price: 100,
      brand: 'DEMON SLAYER',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '1',
      name: 'KATANA',
      category: 'COSPLAY',
      image: './images/product-3.jpg',
      price: 100,
      brand: 'DEMON SLAYER',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '1',
      name: 'KATANA',
      category: 'COSPLAY',
      image: './images/product-4.jpg',
      price: 100,
      brand: 'DEMON SLAYER',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '1',
      name: 'KATANA',
      category: 'COSPLAY',
      image: './images/product-1.jpg',
      price: 100,
      brand: 'DEMON SLAYER',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '1',
      name: 'KATANA',
      category: 'COSPLAY',
      image: './images/product-6.jpg',
      price: 100,
      brand: 'DEMON SLAYER',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '1',
      name: 'KATANA',
      category: 'COSPLAY',
      image: './images/product-6.jpg',
      price: 100,
      brand: 'DEMON SLAYER',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
  ],
};
